# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.client_source_ips_addresses import ClientSourceIpsAddresses

class TestClientSourceIpsAddresses(unittest.TestCase):
    """ClientSourceIpsAddresses unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientSourceIpsAddresses:
        """Test ClientSourceIpsAddresses
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientSourceIpsAddresses`
        """
        model = ClientSourceIpsAddresses()
        if include_optional:
            return ClientSourceIpsAddresses(
                data = [{"name":"123.101.24.13","description":"IP address"},{"name":"39.101.184.53","description":"IP address"},{"name":"33.250.232.96","description":"IP address"},{"name":"174.168.205.80","description":"IP address"},{"name":"243.222.210.249","description":"IP address"},{"name":"50.27.14.222","description":"IP address"}]
            )
        else:
            return ClientSourceIpsAddresses(
                data = [{"name":"123.101.24.13","description":"IP address"},{"name":"39.101.184.53","description":"IP address"},{"name":"33.250.232.96","description":"IP address"},{"name":"174.168.205.80","description":"IP address"},{"name":"243.222.210.249","description":"IP address"},{"name":"50.27.14.222","description":"IP address"}],
        )
        """

    def testClientSourceIpsAddresses(self):
        """Test ClientSourceIpsAddresses"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
