# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.certificates_api import CertificatesApi


class TestCertificatesApi(unittest.TestCase):
    """CertificatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CertificatesApi()

    def tearDown(self) -> None:
        pass

    def test_get_certificate_details(self) -> None:
        """Test case for get_certificate_details

        Show the details of a specific TLS/SSL certificate
        """
        pass

    def test_get_list_certificates(self) -> None:
        """Test case for get_list_certificates

        List all discovered certificates
        """
        pass


if __name__ == '__main__':
    unittest.main()
