# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.service_information_certificate import ServiceInformationCertificate

class TestServiceInformationCertificate(unittest.TestCase):
    """ServiceInformationCertificate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceInformationCertificate:
        """Test ServiceInformationCertificate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceInformationCertificate`
        """
        model = ServiceInformationCertificate()
        if include_optional:
            return ServiceInformationCertificate(
                id = 1,
                subject_common_name = 'example.com',
                subject_organisation = 'example',
                subject_alt_names = ["example.com"],
                subject_country = 'SG',
                issuer_common_name = 'example',
                issuer_organisation = 'example',
                issuer_country = 'SG',
                fingerprint = 'example',
                public_key_info_alg = 'example',
                public_key_info_size = 'example',
                status = 'Expired',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return ServiceInformationCertificate(
                id = 1,
                subject_common_name = 'example.com',
                subject_organisation = 'example',
                subject_alt_names = ["example.com"],
                subject_country = 'SG',
                issuer_common_name = 'example',
                issuer_organisation = 'example',
                issuer_country = 'SG',
                fingerprint = 'example',
                public_key_info_alg = 'example',
                public_key_info_size = 'example',
                status = 'Expired',
        )
        """

    def testServiceInformationCertificate(self):
        """Test ServiceInformationCertificate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
