# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.asset_subdomains_api import AssetSubdomainsApi


class TestAssetSubdomainsApi(unittest.TestCase):
    """AssetSubdomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetSubdomainsApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_subdomain_details(self) -> None:
        """Test case for get_asset_subdomain_details

        Show the details of a a specific Subdomain asset.
        """
        pass

    def test_get_list_asset_subdomains(self) -> None:
        """Test case for get_list_asset_subdomains

        List all discovered Subdomains, ordered by date identified.
        """
        pass

    def test_update_asset_subdomain_status(self) -> None:
        """Test case for update_asset_subdomain_status

        Update status of a specific subdomain asset.
        """
        pass


if __name__ == '__main__':
    unittest.main()
