# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.asset_ports_api import AssetPortsApi


class TestAssetPortsApi(unittest.TestCase):
    """AssetPortsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetPortsApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_port_details(self) -> None:
        """Test case for get_asset_port_details

        Show the details of a specific port asset.
        """
        pass

    def test_get_list_asset_ports(self) -> None:
        """Test case for get_list_asset_ports

        List all discovered ports belonging to IP Addresses, ordered by date identified.
        """
        pass


if __name__ == '__main__':
    unittest.main()
