# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.client_ip_range import ClientIpRange

class TestClientIpRange(unittest.TestCase):
    """ClientIpRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientIpRange:
        """Test ClientIpRange
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientIpRange`
        """
        model = ClientIpRange()
        if include_optional:
            return ClientIpRange(
                type = 'ipRange',
                source = 'test',
                status = 'pending',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                iprange = '105.115.141.50/24',
                asn = 'AS4676',
                desc = 'Mock Turtle at last',
                country = 'SG',
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ]
            )
        else:
            return ClientIpRange(
                type = 'ipRange',
                source = 'test',
                status = 'pending',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                iprange = '105.115.141.50/24',
                asn = 'AS4676',
                desc = 'Mock Turtle at last',
                country = 'SG',
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ],
        )
        """

    def testClientIpRange(self):
        """Test ClientIpRange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
