# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.unauthorized import Unauthorized

class TestUnauthorized(unittest.TestCase):
    """Unauthorized unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Unauthorized:
        """Test Unauthorized
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Unauthorized`
        """
        model = Unauthorized()
        if include_optional:
            return Unauthorized(
                status_code = 401,
                message = 'WT Api Token',
                error = 'UNAUTHORIZED_REQUEST'
            )
        else:
            return Unauthorized(
                error = 'UNAUTHORIZED_REQUEST',
        )
        """

    def testUnauthorized(self):
        """Test Unauthorized"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
