# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.asset_source_code_repositories_api import AssetSourceCodeRepositoriesApi


class TestAssetSourceCodeRepositoriesApi(unittest.TestCase):
    """AssetSourceCodeRepositoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetSourceCodeRepositoriesApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_repository_details(self) -> None:
        """Test case for get_asset_repository_details

        Show the details of a specific Source Code Repository asset.
        """
        pass

    def test_get_list_asset_repositories(self) -> None:
        """Test case for get_list_asset_repositories

        List all discovered Source Code Repositories, ordered by date identified.
        """
        pass

    def test_update_asset_repository_status(self) -> None:
        """Test case for update_asset_repository_status

        Update status of a specific repository asset.
        """
        pass


if __name__ == '__main__':
    unittest.main()
