# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.service_listing import ServiceListing

class TestServiceListing(unittest.TestCase):
    """ServiceListing unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceListing:
        """Test ServiceListing
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceListing`
        """
        model = ServiceListing()
        if include_optional:
            return ServiceListing(
                id = 1,
                port_id = 1,
                ip = '192.168.1.1',
                port = 80,
                type = 'TCP',
                country = 'US',
                banner = 'Apache/2.4.7',
                service = 'HTTPS',
                source = 'auto_add_from_dns_a_record',
                last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                technologies = [
                    watchtowr_api.models.technology.Technology(
                        id = 1, 
                        name = 'APACHE', 
                        version = '0.1', 
                        display_name = 'APACHE', )
                    ],
                service_types = [
                    watchtowr_api.models.service_type.ServiceType(
                        id = 1, 
                        name = 'APACHE', )
                    ],
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ]
            )
        else:
            return ServiceListing(
                id = 1,
                port_id = 1,
                ip = '192.168.1.1',
                last_seen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                technologies = [
                    watchtowr_api.models.technology.Technology(
                        id = 1, 
                        name = 'APACHE', 
                        version = '0.1', 
                        display_name = 'APACHE', )
                    ],
                service_types = [
                    watchtowr_api.models.service_type.ServiceType(
                        id = 1, 
                        name = 'APACHE', )
                    ],
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ],
        )
        """

    def testServiceListing(self):
        """Test ServiceListing"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
