# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.client_activity_log import ClientActivityLog

class TestClientActivityLog(unittest.TestCase):
    """ClientActivityLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientActivityLog:
        """Test ClientActivityLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientActivityLog`
        """
        model = ClientActivityLog()
        if include_optional:
            return ClientActivityLog(
                id = 1,
                description = Successful login from 127.0.0.1,
                type = Successful Login,
                properties = {"attributes": {"ip": "24.11.9.123"}},
                created_at = 2022-02-22 22:00:00,
                caused_by = watchtowr_api.models.causer.Causer(
                    id = 1, 
                    name = Example, )
            )
        else:
            return ClientActivityLog(
                id = 1,
                description = Successful login from 127.0.0.1,
                type = Successful Login,
                caused_by = watchtowr_api.models.causer.Causer(
                    id = 1, 
                    name = Example, ),
        )
        """

    def testClientActivityLog(self):
        """Test ClientActivityLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
