# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.asset_cloud_storage_assets_api import AssetCloudStorageAssetsApi


class TestAssetCloudStorageAssetsApi(unittest.TestCase):
    """AssetCloudStorageAssetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetCloudStorageAssetsApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_cloud_storage_details(self) -> None:
        """Test case for get_asset_cloud_storage_details

        Show the details of a specific Cloud Storage asset.
        """
        pass

    def test_get_list_asset_cloud_storages(self) -> None:
        """Test case for get_list_asset_cloud_storages

        List all discovered Cloud Storage assets, ordered by date identified.
        """
        pass

    def test_update_asset_cloud_storage_status(self) -> None:
        """Test case for update_asset_cloud_storage_status

        Update status of a specific cloud storage asset.
        """
        pass


if __name__ == '__main__':
    unittest.main()
