# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.points_of_interest_api import PointsOfInterestApi


class TestPointsOfInterestApi(unittest.TestCase):
    """PointsOfInterestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PointsOfInterestApi()

    def tearDown(self) -> None:
        pass

    def test_get_list_points_of_interest(self) -> None:
        """Test case for get_list_points_of_interest

        List all discovered Points of Interest.
        """
        pass


if __name__ == '__main__':
    unittest.main()
