# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.source_ip_addresses_api import SourceIPAddressesApi


class TestSourceIPAddressesApi(unittest.TestCase):
    """SourceIPAddressesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SourceIPAddressesApi()

    def tearDown(self) -> None:
        pass

    def test_get_list_source_ip_addresses(self) -> None:
        """Test case for get_list_source_ip_addresses

        List all source IP Addresses.
        """
        pass


if __name__ == '__main__':
    unittest.main()
