# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.finding_list_response import FindingListResponse

class TestFindingListResponse(unittest.TestCase):
    """FindingListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindingListResponse:
        """Test FindingListResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindingListResponse`
        """
        model = FindingListResponse()
        if include_optional:
            return FindingListResponse(
                data = [
                    watchtowr_api.models.client_finding.ClientFinding(
                        id = 1, 
                        title = 'Valid Credentials Discovered In Business System', 
                        description = 'Through watchTowr's Credential Stuffing capabilities, a valid set of credentials have been identified to work to authenticate to a legitimately exposed business system. 

These credentials have been confirmed as valid against the identified system, and are publicly available.', 
                        impact = 'Depending on the system, if leveraged by an attacker it may be possible to:

* Gain access to internal systems
* Gain access to sensitive and confidential data
* Gain VPN access for further internal exploitation and deployment of payloads such as ransomware', 
                        finding_impact = 'Prioritised Findings', 
                        tags = [
                            watchtowr_api.models.client_finding_impact_tag.ClientFindingImpactTag(
                                id = 1, 
                                name = 'CISA-KEV', )
                            ], 
                        evidence = 'URL: https://sso.core.watchtowr.com/adfs/ls

Valid credentials discovered:
Username: dummy
Password: dummy123!

MFA status: Single-factor authentication', 
                        recommendation = 'As a priority, it is recommended that the identified credentials be revoked and rotated. As a follow-up an analysis should also be performed to ensure that the identified credentials have not previously been utilised by an attacker.

As a long-term measure to ensure that the security impact of breach credentials are minimised, it is recommended that:
* Two-factor authentication (2FA) to be enabled for all business systems that support it, which provides an additional layer of security
* Use a Single Sign-On (SSO) service for business systems, where possible
', 
                        severity = 'high', 
                        cvssv3_score = 8.1, 
                        cvssv3_metrics = 'CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N/E:F/RL:W/RC:C', 
                        status = 'confirmed', 
                        created_at = 2022-02-13T02:10:00.000000Z, 
                        affected = watchtowr_api.models.affected.affected(), 
                        cve_id = 'CVE-2023-38180', 
                        epss_score = 0.97521, 
                        retest = watchtowr_api.models.retest.Retest(
                            retest_remaining = 1, 
                            current_retest = watchtowr_api.models.finding_retest_response_dto.FindingRetestResponseDto(
                                requested_by = 'Requested by user', 
                                requested_at = '2024-01-29T08:05:09Z', 
                                retest_status = 'success', 
                                status_occurred_at = '2024-01-29T08:05:09Z', 
                                completed_at = '2024-01-29T08:05:09Z', 
                                evidence = 'Evidence for retest', ), ), 
                        finding_retests = [
                            watchtowr_api.models.finding_retest_response_dto.FindingRetestResponseDto(
                                requested_by = 'Requested by user', 
                                requested_at = '2024-01-29T08:05:09Z', 
                                retest_status = 'success', 
                                status_occurred_at = '2024-01-29T08:05:09Z', 
                                completed_at = '2024-01-29T08:05:09Z', 
                                evidence = 'Evidence for retest', )
                            ], 
                        assigned_user = watchtowr_api.models.client_finding_assignee.ClientFindingAssignee(
                            name = 'Some user name', ), )
                    ],
                meta = watchtowr_api.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, )
            )
        else:
            return FindingListResponse(
                data = [
                    watchtowr_api.models.client_finding.ClientFinding(
                        id = 1, 
                        title = 'Valid Credentials Discovered In Business System', 
                        description = 'Through watchTowr's Credential Stuffing capabilities, a valid set of credentials have been identified to work to authenticate to a legitimately exposed business system. 

These credentials have been confirmed as valid against the identified system, and are publicly available.', 
                        impact = 'Depending on the system, if leveraged by an attacker it may be possible to:

* Gain access to internal systems
* Gain access to sensitive and confidential data
* Gain VPN access for further internal exploitation and deployment of payloads such as ransomware', 
                        finding_impact = 'Prioritised Findings', 
                        tags = [
                            watchtowr_api.models.client_finding_impact_tag.ClientFindingImpactTag(
                                id = 1, 
                                name = 'CISA-KEV', )
                            ], 
                        evidence = 'URL: https://sso.core.watchtowr.com/adfs/ls

Valid credentials discovered:
Username: dummy
Password: dummy123!

MFA status: Single-factor authentication', 
                        recommendation = 'As a priority, it is recommended that the identified credentials be revoked and rotated. As a follow-up an analysis should also be performed to ensure that the identified credentials have not previously been utilised by an attacker.

As a long-term measure to ensure that the security impact of breach credentials are minimised, it is recommended that:
* Two-factor authentication (2FA) to be enabled for all business systems that support it, which provides an additional layer of security
* Use a Single Sign-On (SSO) service for business systems, where possible
', 
                        severity = 'high', 
                        cvssv3_score = 8.1, 
                        cvssv3_metrics = 'CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N/E:F/RL:W/RC:C', 
                        status = 'confirmed', 
                        created_at = 2022-02-13T02:10:00.000000Z, 
                        affected = watchtowr_api.models.affected.affected(), 
                        cve_id = 'CVE-2023-38180', 
                        epss_score = 0.97521, 
                        retest = watchtowr_api.models.retest.Retest(
                            retest_remaining = 1, 
                            current_retest = watchtowr_api.models.finding_retest_response_dto.FindingRetestResponseDto(
                                requested_by = 'Requested by user', 
                                requested_at = '2024-01-29T08:05:09Z', 
                                retest_status = 'success', 
                                status_occurred_at = '2024-01-29T08:05:09Z', 
                                completed_at = '2024-01-29T08:05:09Z', 
                                evidence = 'Evidence for retest', ), ), 
                        finding_retests = [
                            watchtowr_api.models.finding_retest_response_dto.FindingRetestResponseDto(
                                requested_by = 'Requested by user', 
                                requested_at = '2024-01-29T08:05:09Z', 
                                retest_status = 'success', 
                                status_occurred_at = '2024-01-29T08:05:09Z', 
                                completed_at = '2024-01-29T08:05:09Z', 
                                evidence = 'Evidence for retest', )
                            ], 
                        assigned_user = watchtowr_api.models.client_finding_assignee.ClientFindingAssignee(
                            name = 'Some user name', ), )
                    ],
                meta = watchtowr_api.models.meta.Meta(
                    pagination = {"total":20,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"previous":"url","next":"url"}}, ),
        )
        """

    def testFindingListResponse(self):
        """Test FindingListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
