# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.hunts_api import HuntsApi


class TestHuntsApi(unittest.TestCase):
    """HuntsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HuntsApi()

    def tearDown(self) -> None:
        pass

    def test_get_client_hunts(self) -> None:
        """Test case for get_client_hunts

        List all hunts
        """
        pass

    def test_get_list_asset_by_hunt(self) -> None:
        """Test case for get_list_asset_by_hunt

        Get list assets of specific hunt
        """
        pass

    def test_get_list_finding_by_hunt(self) -> None:
        """Test case for get_list_finding_by_hunt

        Get list findings of specific hunt
        """
        pass

    def test_show_the_detail_hunt(self) -> None:
        """Test case for show_the_detail_hunt

        Show the detail of specific hunt
        """
        pass


if __name__ == '__main__':
    unittest.main()
