# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.add_asset_api import AddAssetApi


class TestAddAssetApi(unittest.TestCase):
    """AddAssetApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AddAssetApi()

    def tearDown(self) -> None:
        pass

    def test_submit_asset(self) -> None:
        """Test case for submit_asset

        Add asset to your attack surface for review.
        """
        pass


if __name__ == '__main__':
    unittest.main()
