# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.create_client_seed_data_request_body import CreateClientSeedDataRequestBody

class TestCreateClientSeedDataRequestBody(unittest.TestCase):
    """CreateClientSeedDataRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateClientSeedDataRequestBody:
        """Test CreateClientSeedDataRequestBody
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateClientSeedDataRequestBody`
        """
        model = CreateClientSeedDataRequestBody()
        if include_optional:
            return CreateClientSeedDataRequestBody(
                data = [{"title":"New asset","type":"domain","value":"www.example.com"},{"title":"New IP","type":"ip","value":"192.158.1.38"}],
                business_units = [{"id":-1,"type":"UNASSIGNED"},{"id":1,"type":"BUSINESS_UNIT"}]
            )
        else:
            return CreateClientSeedDataRequestBody(
                data = [{"title":"New asset","type":"domain","value":"www.example.com"},{"title":"New IP","type":"ip","value":"192.158.1.38"}],
        )
        """

    def testCreateClientSeedDataRequestBody(self):
        """Test CreateClientSeedDataRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
