# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.client_port import ClientPort

class TestClientPort(unittest.TestCase):
    """ClientPort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ClientPort:
        """Test ClientPort
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClientPort`
        """
        model = ClientPort()
        if include_optional:
            return ClientPort(
                type = 'TCP',
                status = 'verified',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                ip = '45.33.32.156',
                ip_id = 333,
                port = 22,
                banner = 'OpenSSH6.6.1p1 Ubuntu 2ubuntu2.13Ubuntu Linux; protocol 2.0',
                service = 'ssh',
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ]
            )
        else:
            return ClientPort(
                type = 'TCP',
                status = 'verified',
                created_at = 2022-02-13T02:10:00.000000Z,
                updated_at = 2022-02-13T02:10:00.000000Z,
                deleted_at = 2022-02-13T02:10:00.000000Z,
                id = 123,
                ip = '45.33.32.156',
                ip_id = 333,
                port = 22,
                banner = 'OpenSSH6.6.1p1 Ubuntu 2ubuntu2.13Ubuntu Linux; protocol 2.0',
                service = 'ssh',
                business_units = [
                    watchtowr_api.models.client_business_unit.ClientBusinessUnit(
                        id = 1, 
                        name = 'Singapore Business Unit', )
                    ],
        )
        """

    def testClientPort(self):
        """Test ClientPort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
