# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.findings_api import FindingsApi


class TestFindingsApi(unittest.TestCase):
    """FindingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FindingsApi()

    def tearDown(self) -> None:
        pass

    def test_export_pdf_for_finding(self) -> None:
        """Test case for export_pdf_for_finding

        Export a PDF of a specific finding
        """
        pass

    def test_get_available_finding_statuses(self) -> None:
        """Test case for get_available_finding_statuses

        List the available statuses for a finding.
        """
        pass

    def test_get_finding_details(self) -> None:
        """Test case for get_finding_details

        Show the detail of a specific finding
        """
        pass

    def test_get_list_findings(self) -> None:
        """Test case for get_list_findings

        List all discovered findings, ordered by date identified.
        """
        pass

    def test_start_specific_finding_retest(self) -> None:
        """Test case for start_specific_finding_retest

        Start specific finding retest
        """
        pass

    def test_update_finding_status(self) -> None:
        """Test case for update_finding_status

        Update the status of a finding.
        """
        pass


if __name__ == '__main__':
    unittest.main()
