# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.pagination import Pagination

class TestPagination(unittest.TestCase):
    """Pagination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Pagination:
        """Test Pagination
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Pagination`
        """
        model = Pagination()
        if include_optional:
            return Pagination(
                total = 1.337,
                count = 1.337,
                per_page = 1.337,
                current_page = 1.337,
                total_pages = 1.337,
                links = watchtowr_api.models.link.Link(
                    previous = '', 
                    next = '', )
            )
        else:
            return Pagination(
                total = 1.337,
                count = 1.337,
                per_page = 1.337,
                current_page = 1.337,
                total_pages = 1.337,
                links = watchtowr_api.models.link.Link(
                    previous = '', 
                    next = '', ),
        )
        """

    def testPagination(self):
        """Test Pagination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
