# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.api.asset_domains_api import AssetDomainsApi


class TestAssetDomainsApi(unittest.TestCase):
    """AssetDomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AssetDomainsApi()

    def tearDown(self) -> None:
        pass

    def test_get_asset_domain_details(self) -> None:
        """Test case for get_asset_domain_details

        Show the details of a specific Domain asset.
        """
        pass

    def test_get_list_asset_domains(self) -> None:
        """Test case for get_list_asset_domains

        List all discovered Domains, ordered by date identified.
        """
        pass

    def test_update_asset_domain_status(self) -> None:
        """Test case for update_asset_domain_status

        Update status of a specific domain asset.
        """
        pass


if __name__ == '__main__':
    unittest.main()
