# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.technology import Technology

class TestTechnology(unittest.TestCase):
    """Technology unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Technology:
        """Test Technology
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Technology`
        """
        model = Technology()
        if include_optional:
            return Technology(
                id = 1,
                name = 'APACHE',
                version = '0.1',
                display_name = 'APACHE'
            )
        else:
            return Technology(
                id = 1,
                name = 'APACHE',
                version = '0.1',
                display_name = 'APACHE',
        )
        """

    def testTechnology(self):
        """Test Technology"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
