# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.unprocessable_content import UnprocessableContent

class TestUnprocessableContent(unittest.TestCase):
    """UnprocessableContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UnprocessableContent:
        """Test UnprocessableContent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UnprocessableContent`
        """
        model = UnprocessableContent()
        if include_optional:
            return UnprocessableContent(
                message = 'The given data was invalid.',
                status_code = 422,
                errors = {"xxx":["The xxx field is required.","The selected xxx is invalid.","..."]}
            )
        else:
            return UnprocessableContent(
                message = 'The given data was invalid.',
                status_code = 422,
                errors = {"xxx":["The xxx field is required.","The selected xxx is invalid.","..."]},
        )
        """

    def testUnprocessableContent(self):
        """Test UnprocessableContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
