# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from watchtowr_api.models.asset import Asset

class TestAsset(unittest.TestCase):
    """Asset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Asset:
        """Test Asset
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Asset`
        """
        model = Asset()
        if include_optional:
            return Asset(
                id = '11',
                created_at = '2021-11-22T22:17:12Z',
                source = 'module-github-enumeration-v0.1',
                type = 'repository',
                status = 'verified',
                name = 'TestName',
                country = '',
                platform = '',
                provider = 'github',
                url = 'https://example.com',
                business_units = [],
                discovery_reason = '',
                owner = 'example_user',
                live = True,
                metadata = {}
            )
        else:
            return Asset(
                id = '11',
                created_at = '2021-11-22T22:17:12Z',
                source = 'module-github-enumeration-v0.1',
                type = 'repository',
                status = 'verified',
                name = 'TestName',
                country = '',
                platform = '',
                provider = 'github',
                url = 'https://example.com',
                business_units = [],
                discovery_reason = '',
                owner = 'example_user',
                live = True,
                metadata = {},
        )
        """

    def testAsset(self):
        """Test Asset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
