# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from watchtowr_api.models.client_finding_assignee import ClientFindingAssignee
from watchtowr_api.models.client_finding_impact_tag import ClientFindingImpactTag
from watchtowr_api.models.finding_retest_response_dto import FindingRetestResponseDto
from watchtowr_api.models.retest import Retest
from typing import Optional, Set
from typing_extensions import Self

class ClientFinding(BaseModel):
    """
    ClientFinding
    """ # noqa: E501
    id: Union[StrictFloat, StrictInt]
    title: StrictStr
    description: StrictStr
    impact: StrictStr
    finding_impact: StrictStr
    tags: List[ClientFindingImpactTag]
    evidence: StrictStr
    recommendation: StrictStr
    severity: StrictStr
    cvssv3_score: Union[StrictFloat, StrictInt]
    cvssv3_metrics: StrictStr
    status: StrictStr
    created_at: Dict[str, Any]
    affected: Dict[str, Any]
    cve_id: Optional[StrictStr] = None
    epss_score: Optional[Union[StrictFloat, StrictInt]] = None
    retest: Optional[Retest] = None
    finding_retests: List[FindingRetestResponseDto]
    assigned_user: ClientFindingAssignee
    __properties: ClassVar[List[str]] = ["id", "title", "description", "impact", "finding_impact", "tags", "evidence", "recommendation", "severity", "cvssv3_score", "cvssv3_metrics", "status", "created_at", "affected", "cve_id", "epss_score", "retest", "finding_retests", "assigned_user"]

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['critical', 'high', 'medium', 'low', 'info']):
            raise ValueError("must be one of enum values ('critical', 'high', 'medium', 'low', 'info')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['confirmed', 'unconfirmed', 'remediated', 'risk-accepted', 'closed', 'asset-no-longer-tracked']):
            raise ValueError("must be one of enum values ('confirmed', 'unconfirmed', 'remediated', 'risk-accepted', 'closed', 'asset-no-longer-tracked')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClientFinding from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item in self.tags:
                if _item:
                    _items.append(_item.to_dict())
            _dict['tags'] = _items
        # override the default output from pydantic by calling `to_dict()` of retest
        if self.retest:
            _dict['retest'] = self.retest.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in finding_retests (list)
        _items = []
        if self.finding_retests:
            for _item in self.finding_retests:
                if _item:
                    _items.append(_item.to_dict())
            _dict['finding_retests'] = _items
        # override the default output from pydantic by calling `to_dict()` of assigned_user
        if self.assigned_user:
            _dict['assigned_user'] = self.assigned_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClientFinding from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "impact": obj.get("impact"),
            "finding_impact": obj.get("finding_impact"),
            "tags": [ClientFindingImpactTag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None,
            "evidence": obj.get("evidence"),
            "recommendation": obj.get("recommendation"),
            "severity": obj.get("severity"),
            "cvssv3_score": obj.get("cvssv3_score"),
            "cvssv3_metrics": obj.get("cvssv3_metrics"),
            "status": obj.get("status"),
            "created_at": obj.get("created_at"),
            "affected": obj.get("affected"),
            "cve_id": obj.get("cve_id"),
            "epss_score": obj.get("epss_score"),
            "retest": Retest.from_dict(obj["retest"]) if obj.get("retest") is not None else None,
            "finding_retests": [FindingRetestResponseDto.from_dict(_item) for _item in obj["finding_retests"]] if obj.get("finding_retests") is not None else None,
            "assigned_user": ClientFindingAssignee.from_dict(obj["assigned_user"]) if obj.get("assigned_user") is not None else None
        })
        return _obj


