# coding: utf-8

"""
    watchTowr Platform Client API SDK

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr

class NotFound(BaseModel):
    """
    NotFound
    """
    message: StrictStr = Field(...)
    status_code: Union[StrictFloat, StrictInt] = Field(..., alias="statusCode")
    __properties = ["message", "statusCode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NotFound:
        """Create an instance of NotFound from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NotFound:
        """Create an instance of NotFound from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NotFound.parse_obj(obj)

        _obj = NotFound.parse_obj({
            "message": obj.get("message"),
            "status_code": obj.get("statusCode")
        })
        return _obj


