# coding: utf-8

"""
    watchTowr Platform Client API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from watchtowr_api.models.whois_data import WhoisData
from typing import Optional, Set
from typing_extensions import Self

class SuspiciousDomain(BaseModel):
    """
    SuspiciousDomain
    """ # noqa: E501
    id: Union[StrictFloat, StrictInt] = Field(description="ID")
    name: StrictStr = Field(description="Name")
    discovery_reason: StrictStr = Field(description="Discovery Reason")
    status: StrictStr
    whois_data: List[WhoisData] = Field(alias="whoisData")
    created_at: Optional[datetime] = Field(default=None, description="Discovery date")
    __properties: ClassVar[List[str]] = ["id", "name", "discovery_reason", "status", "whoisData", "created_at"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pending', 'malicious', 'legitimate']):
            raise ValueError("must be one of enum values ('pending', 'malicious', 'legitimate')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SuspiciousDomain from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in whois_data (list)
        _items = []
        if self.whois_data:
            for _item in self.whois_data:
                if _item:
                    _items.append(_item.to_dict())
            _dict['whoisData'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SuspiciousDomain from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "discovery_reason": obj.get("discovery_reason"),
            "status": obj.get("status"),
            "whoisData": [WhoisData.from_dict(_item) for _item in obj["whoisData"]] if obj.get("whoisData") is not None else None,
            "created_at": obj.get("created_at")
        })
        return _obj


